---
version: "2"
linters:
  default: all
  disable:
    # it should improve to support more known patterns
    - varnamelen
    # why even we have this?
    - nolintlint
    - depguard
    - revive
    - gosec
    - noinlineerr
