---
project_name: gosimac

release:
  github:
    owner: 1995parham
    name: gosimac

checksum: {}

builds:
  - binary: gosimac
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: ./main.go

archives:
  - id: binary
    format: binary
  - id: default
    format: tar.gz
