---
project_name: gosimac

release:
  github:
    owner: 1995parham
    name: gosimac

builds:
  - binary: gosimac
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - "386"
    goarm:
      - "6"
    main: ./main.go
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{
    .Arm }}{{ end }}'
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
