---
language: go
go:
  - "1.13"

env:
  global:
    - secure: OgbslJsC6Gxh5gQ7LXHoJFp06y/6nQ/GYcgAUVEr9wQbLAM5WXWgY19M36tX6Zcoy5MAS5PeIqDmTKkP0TbMhNsPSRntCdNLg6RJ51kS3Ge+kMXFgNlmj0pKkVPjvpJsB5H/xl9Ms2wX4p7nZY9eAsXoO0MyVl48OsGgPm2UzZqBwQtkkUWoKtpkHUvmqfTmQBh8+IhyvVkPgblAOe5vLwCXTlQ2qbRq/hhpSOS8+13iAzucHoaJcXcU/VTvMdYPZfZWWEW+B4XBmldDyaBbddgMdtTCLzsUxS/a4nB39cNUJW+IWW/KuveMdPw+IDKDVyQjhcj8KbWGojvl52B3MJe4fx8lXCbqNMGhVxNs0kZnu6lV20wlsOlKqLcty41DLNxgzOq0LHJ+AuhYUyZgHGmYYR5SI/4Ksc6FyV5tvrvuaT/8oCOhQiIeAZ9BCxQBy2yIA2TFN33qjzdCuen2vT9kJSYB/E+Bw85ihFJgYp/mHu7qRQZBJPBhSyWVTDVO5/SDEhkUEF+Z6r6/YfoFnUdqrAQh8M2nwfN/6rhvR2z11YaPhv9X81z+KV4fCDfJfbfMHG874W7sk/nQWq0zmBHiblbVmi5OfTqDWE2S5ITYlCnsDqBemaLhcArPdsY9n8xLsMLrrqCuyrdnDKEbzItIOYteYKFohgCPSol0rlg=
  matrix:
    - GO111MODULE=on


before_install:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1

install:
  - go mod tidy
  - go mod download
script:
  - golangci-lint run --enable-all
  - go test -v ./...

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
